name: template-deploy

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'dotnet version to install'
        required: false
        type: string
        default: '6.0.x'
      dotnet-prerelease:
        required: false
        type: boolean
        default: false
      deploy-web-app-name:
        description: 'name of the azure app only needed if deploy web app is true'
        required: false
        type: string
      deploy-web-app-slot-name:
        description: 'name of the azure app slot name only needed if deploy web app is true'
        required: false
        type: string
        default: 'production'
      working-directory:
        required: false
        type: string
        default: './src'
    secrets:
      publish-profile:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup dotnet version
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ inputs.dotnet-version }}
          include-prerelease: ${{ inputs.dotnet-prerelease }}
          
      - name: publish
        run: dotnet publish ${{ inputs.working-directory }} -c Release --runtime win-x64 --self-contained -o ${{env.DOTNET_ROOT}}/${{ inputs.deploy-web-app-name }}

      - name: deploy to azure
        uses: azure/webapps-deploy@v2
        with: 
            app-name: ${{ inputs.deploy-web-app-name }}
            slot-name: ${{ inputs.deploy-web-app-slot-name }}
            publish-profile: ${{ secrets.publish-profile }}
            package: ${{ inputs.deploy-web-app-name }}
