name: template-pipeline

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'dotnet version to install'
        required: false
        type: string
        default: '6.0.x'
      dotnet-quality:
        required: false
        type: string
        default: 'ga'
      publish-coverage:
        required: false
        type: boolean
        default: false
      deploy-web-app:
        required: false
        type: boolean
        default: false
      deploy-condition:
        required: false
        type: string
      deploy-web-app-name:
        description: 'name of the azure app only needed if deploy web app is true'
        required: false
        type: string
      deploy-web-app-slot-name:
        description: 'name of the azure app slot name only needed if deploy web app is true'
        required: false
        type: string
        default: 'production'
      check-eslint:
        description: 'path to script folder if you want to check ES6 compliant'
        required: false
        type: string
      working-directory:
        required: false
        type: string
        default: './src'
      publish-directory:
        required: false
        type: string
        default: './'
    secrets:
      publish-profile:
        required: false

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install eslint
        if: ${{ inputs.check-eslint != null }}
        run: npm i -g eslint

      - name: Check JS is ES6 compliant
        if: ${{ inputs.check-eslint != null }}
        run: eslint --env 'es6' ${{ inputs.check-eslint }}

      - name: Setup dotnet version
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ inputs.dotnet-version }}
          dotnet-quality: ${{ inputs.dotnet-quality }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --no-restore --blame-hang --blame-hang-timeout 60s /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverage' /p:ExcludeByFile='**/*.g.cs' /p:Include='[MudBlazor]*' /p:SkipAutoProps=true /p:CoverletOutput='./TestResults/'

      - name: Coverage
        if: ${{ inputs.publish-coverage == true }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.cobertura.xml

      - name: Publish
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (inputs.deploy-web-app == true && github.repository_owner == 'MudBlazor' && github.ref == inputs.deploy-condition) }}
        run: dotnet publish ${{ inputs.publish-directory }} -c Release --runtime win-x64 --self-contained -o ${{env.DOTNET_ROOT}}/${{ inputs.deploy-web-app-name }}
        
      - uses: actions/upload-artifact@v3
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (inputs.deploy-web-app == true && github.repository_owner == 'MudBlazor' && github.ref == inputs.deploy-condition) }}
        with:
          name: ${{ inputs.deploy-web-app-name }}
          path: ${{env.DOTNET_ROOT}}/${{ inputs.deploy-web-app-name }}

  cd:
    name: Deploy
    needs: ci
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (inputs.deploy-web-app == true && github.repository_owner == 'MudBlazor' && github.ref == inputs.deploy-condition) }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: ${{ inputs.deploy-web-app-name }}
          path: ${{ inputs.deploy-web-app-name }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with: 
            app-name: ${{ inputs.deploy-web-app-name }}
            slot-name: ${{ inputs.deploy-web-app-slot-name }}
            publish-profile: ${{ secrets.publish-profile }}
            package: ${{ inputs.deploy-web-app-name }}
